<?php
include_once ('Circle.php');
class Cylinder extends Circle{
    public $height;
    public function __construct($radius, $color,$height)
    {
        parent::__construct($radius, $color);
        $this->height=$height;
    }
    public function getHeight(){
        return $this->height;
    }
    public function setHeight($height){
        $this->height=$height;
    }
    public function getVolum()
    {
        return parent::getArea()*2+parent::getP()*$this->height; // TODO: Change the autogenerated stub
    }
    public function toString()
    {
        return parent::toString().'<br>'.'Volum: '.$this->getVolum(); // TODO: Change the autogenerated stub
    }

}